### ISSUE TITLE
turn IP into digit

### ISSUE THREAD

**Issue by redimongo** [whitequark/ipaddr.js#167]
Wondering if it is possible to turn an IPv4 and ipv6 into decimals so that we can do greater and lesser searches in Database.

**Comment by Uzlopak** [comment]
You could do it. Atleast with IPv4 it is easy, as it has a long number notation. 

co-pilot gave me this function. it is not implemented for performance.
```javascript
function ipv42Tont(ip) {
  return ip.split('.').reduce(function(ipInt, octet) { return (ipInt<<8) + parseInt(octet, 10)}, 0) >>> 0;
}
```

I wrote the reverse function, because I needed it for something else, and it is optimized for perf. Maybe easier to understand:

```javascript
/**
 * Converts a long IP to a decimal IP.
 * @param {string} longIp
 * @returns {string}
 */
function longIpToDecimal(longIp) {
  longIp = parseInt(longIp, 10)

  return longIp > 4294967295
    ? ''
    : `${longIp >>> 24}.${longIp >>> 16 & 255}.${longIp >>> 8 & 255}.${longIp & 255}`
}
```

You could do the same with IPv6, but as IPv6 is 128 bits, the number is also quiet big. I would recommend that instead of transforming the IPv6 to an integer, to check if you can just transform it to a string. Basically:

`FE80:CD00:0000:0CDE:1257:0000:211E:729C` could be written as 
''\xFE\x80\xCD\x00\x00\x00\x0C\xDE\x12\x57\x00\x00\x21\x1E\x72\x9C'
'\uFE80\uCD00\u0000\u0CDE\u1257\u0000\u211E\u729C'

You should store the string into a database and check if it sorts correctly. You have to take care of the collation, and you have to  ensure, that when using Unicode it still works with surrogates.

**Comment by whitequark** [comment]
Closed this as soon as I read to "Copilot".
