### ISSUE TITLE
4to6 Address

### ISSUE THREAD

**Issue by fantom-x** [whitequark/ipaddr.js#62]
HI, trying to use "ipaddr.js" for 4to6 addresses, and getting weird behaviour: toString() prints the wrong address. Am I doing something wrong? ipaddr.IPv6.isIPv6 does return "true", so it is indeed recognized an ipv6 address. Is there a way to get it printed in a proper format?

```
console.log(">>>>>", ipaddr.parse('::ffff:192.168.1.1').toString());
>>>>> ::ffff:c0a8:101

console.log(">>>>>", ipaddr.parse('::ffff:100.160.78.136').toString());
>>>>> ::ffff:64a0:4e88
```

**Comment by whitequark** [comment]
It's *a* proper format. Both `::ffff:192.168.1.1` and `::ffff:c0a8:101` represent the same address and are equivalent for all intents and purposes. There could be a change to `toString` such that 6to4 addresses would be always printed in the decimal form, if you send a PR I will accept it.

**Comment by JamesMGreene** [comment]
@fantom-x: So I'm unclear as to what your desired output would be. Do you want it to be displayed in its original 4to6 format? e.g.

```js
console.log(">>>>>", ipaddr.parse('::ffff:192.168.1.1').toString());
// >>>>> ::ffff:192.168.1.1

console.log(">>>>>", ipaddr.parse('::ffff:100.160.78.136').toString());
// >>>>> ::ffff:100.160.78.136
```

Or do you want it to display the IPv4 version instead? e.g.

```js
console.log(">>>>>", ipaddr.parse('::ffff:192.168.1.1').toString());
// >>>>> 192.168.1.1

console.log(">>>>>", ipaddr.parse('::ffff:100.160.78.136').toString());
// >>>>> 100.160.78.136
```

---

If you want the latter, you can already do that by using `ipaddr.process` instead of `ipaddr.parse`.

If you want the former, a PR would be necessary as @whitequark already mentioned.
